### ISSUE TITLE
How to install this extension

### ISSUE THREAD

**Issue by ghost** [Richienb/scratch-http#1]
Hello ! 
I search on internet and idk how to install an extension on scratch from github

Thanks

**Comment by Richienb** [comment]
Third-party extensions are not officially supported, so you'll need to [load it in a modded fork](https://sheeptester.github.io/scratch-gui/?extension=https://gistcdn.githack.com/Richienb/eef51075ecd786337b780a780d7ffb5c/raw/c9b1c9bbac1fd3e28d16122615f746f4d11e7228/index.js).
